name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        image_path: [./health-check, ./goat-home]
        include:
          - image_path: ./health-check
            image_name: he-ch-test-name
          - image_path: ./goat-home
            image_name: go-ho-test-name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          echo ${{ matrix.image_name }}
          docker build -t ${{ matrix.image_name }}:${{ github.sha }} ${{ matrix.image_path }} 

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ matrix.image_name }}:${{ github.sha }}'
          format: 'sarif'
          severity: 'CRITICAL'
          output: 'trivy-results-${{ matrix.image_name }}.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results-${{ matrix.image_name }}.sarif'
